# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "migrations"
fail_fast: true

repos:
  - repo: local
    hooks:
    - id: ruff-check
      name: ruff check
      language: system
      entry: ruff check --force-exclude --fix --show-fixes --preview
      types:
        - python
    - id: pytest
      name: pytest
      language: system
      entry: python -m pytest test/ -q
      types:
        - python
      pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
